Week 1 folder & regex research added
fac-13/research pull request #2
Opened 2018-02-27 18:30 UTC by vlb834

2018-02-27 18:34 UTC, lucymk commented on week-1/RegexResearch.md
> +## Presentation Link with Repl examples
I wonder if it might be better to put the presentation link at the top, to allow for easier access? 😃

2018-02-27 18:35 UTC, lucymk requested changes
I wonder if it might be better to put the presentation link at the top, to allow for easier access? 😃

2018-02-27 23:15 UTC, vlb834 commented
@lucymk  I moved the presentation link up to the top :)

2018-02-27 23:21 UTC, vlb834 commented
@lucymk  Also now added link to main Readme.

2018-02-28 10:00 UTC, lucymk approved these changes

2018-02-28 10:00 UTC, merged